# Generated by Django 3.2.10 on 2022-02-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_postcreate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='endereco_url',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
