# Generated by Django 3.2.10 on 2022-02-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_endereco_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='endereco_url',
        ),
    ]
