# Generated by Django 3.2.10 on 2022-02-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_endereco_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='endereco_url',
            new_name='slug',
        ),
    ]
