# Generated by Django 3.2.10 on 2022-02-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220222_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
