# Generated by Django 3.2.10 on 2022-02-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_comments_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='post',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
    ]
