# Generated by Django 4.0.4 on 2022-05-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220224_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
