# Generated by Django 3.2.10 on 2022-02-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='perfil',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
