# Generated by Django 4.0.4 on 2022-05-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20220218_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
