# Generated by Django 4.0.4 on 2022-05-24 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0015_remove_likes_comment_remove_likes_post_and_more'),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0)),
                ('comment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='comments.comments')),
                ('post', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
